services:
  app-dev:
    image: amazoncorretto:25
    profiles:
      - dev
    working_dir: /workspace
    volumes:
      - .:/workspace
      - maven-repo:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: dev
    command: >
      sh -c "./mvnw -pl mono-infrastructure -am -DskipTests package
      && java -jar mono-infrastructure/target/*-infrastructure-*.jar"
    ports:
      - "8080:8080"

  app-prod:
    image: amazoncorretto:25
    profiles:
      - prod
    working_dir: /workspace
    volumes:
      - .:/workspace
      - maven-repo:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: prod
    command: >
      sh -c "./mvnw -pl mono-infrastructure -am -DskipTests package
      && java -jar mono-infrastructure/target/*-infrastructure-*.jar"
    ports:
      - "8080:8080"

volumes:
  maven-repo:
