services:
  portfolio:
    image: portfolio
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: ${PROFILE:-pro}
    container_name: portfolio
    env_file:
      - .env.${PROFILE:-pro}
    ports:
      - "${PORT:-4173}:4173"
    restart: unless-stopped
    command: ["node", "./dist/server/entry.mjs"]
