# SonarQube configuration for SpringBootTemplate
sonar.projectKey=SpringBootTemplate
sonar.projectName=SpringBootTemplate
sonar.java.binaries=**/target/classes
sonar.sources=.
sonar.language=java
sonar.sourceEncoding=UTF-8
# Regla personalizada: prohibir inyección por campo
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S6813
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java
